### PR TITLE
Automate Stylesheet and Script Purges

### PR DESCRIPTION
**Pull request by cyberknet**
Added support for UmbracoFlare to automatically purge scripts and stylesheets when they are edited through the backend - resolves Issue #12

### CODE REVIEW

**Comment by cyberknet** [comment]
Any thoughts on this PR? I've been running it these past two days on my site and it's been working perfectly.

**Comment by cyberknet** [comment]
Just checking in - have you had a chance to review this pull request yet? It was a pretty small change. It is still working fine on my site. I can maintain a patch if I need to, but I'd much prefer to have the change integrated upstream :)

**Comment by markadrake** [comment]
Hey @cyberknet - just saw this. I will review with the team on Tuesday and will make either (a) feedback or (b) merging this a priority! We have a number of sites using UmbracoFlare so it would be good to try it across a few different installations just to make sure. Thanks for your contribution!

**Comment by cyberknet** [comment]
Thanks so much - let me know if you end up with feedback and I will make any necessary changes.

**Comment by cyberknet** [comment]
@markadrake @jmcaveney Were you able to review this with the team last Tuesday? If not, on the agenda for tomorrow?

**Comment by cyberknet** [comment]
@markadrake @jmcaveney Not sure what the usual integration schedule is like, but it's been a month here and honestly no meaningful feedback yet. The patch isn't overly large, and the functionality is pretty small. I do believe the intent is good... so I was wondering if can you give me some insight on what the hold up is please?

**Comment by jmcaveney** [comment]
sorry for the long delay here, had some family issues in October to take care of and have been playing catchup since. thank you for the pull request, looks good.

**Comment by cyberknet** [comment]
Thanks for merging this. I know it can be hectic trying to balance OSS projects and pay-the-bills activities. I appreciate your time.

**Pull request merged**
